---
title: "Flex Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns 
    vertical_layout: scroll 
    social: ["menu"]
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(palmerpenguins)
library(plotly)
library(DT)
library(fontawesome)
# checkout datatables.net to see all options for data\
# htmlwidgets.org showcases several widgets 

data("penguins")

```

Plots
=======================================================================
Column {data-width=650}
-----------------------------------------------------------------------

### Scatter plot of bill length and depth 

```{r}

plot_a <- penguins %>% ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +
  geom_point()
plotly::ggplotly(plot_a)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

penguins %>% ggplot(aes(x = body_mass_g, y = sex, fill = sex)) +
  geom_boxplot()

```

### Chart C

```{r}

penguins %>% ggplot(aes(x = flipper_length_mm, fill = species)) +
  geom_histogram() +
  facet_wrap(~species)

```

Data
=======================================================================
```{r}
# checkout datatables.net to see all options for data
penguins %>% datatable(extensions = "Buttons",
                       options = list(dom = "Blfrtip",
                                      buttons = c("copy", "csv", "excel", "pdf", "print")))
```

